import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import '../globals.css';
import Link from 'next/link';
import {ReactNode} from 'react';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function AuthLayout({children}: Readonly<{children: ReactNode}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <header className="sticky top-0 z-50 w-full border-b bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
                    <div className="container mx-auto px-4 py-4">
                        <nav className="flex items-center justify-between">
                            <div className="text-xl font-bold">Your Logo</div>
                            <ul className="flex gap-6">
                                <li>
                                    <Link href="/login" className="hover:text-gray-600">
                                        Login
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/register" className="hover:text-gray-600">
                                        Register
                                    </Link>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </header>

                <main className="flex-1 container mx-auto px-4 py-8">{children}</main>

                <footer className="border-t bg-gray-50">
                    <div className="container mx-auto px-4 py-8">
                        <div className="mt-8 pt-8 border-t text-center text-gray-600">
                            <p>
                                &copy; {new Date().getFullYear()} Your Company. All rights reserved.
                            </p>
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    );
}
